# Generated by Django 3.0 on 2021-01-10 06:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomor_Disposisi', models.CharField(max_length=100, unique=True)),
                ('Nomor_Agenda_tu', models.CharField(max_length=100)),
                ('Nomor_Surat', models.CharField(max_length=100, unique=True)),
                ('Diterima', models.CharField(max_length=100)),
                ('Tanggal_Surat', models.DateField()),
                ('Tanggal_Surat_Akhir', models.DateField()),
                ('Bagian', multiselectfield.db.fields.MultiSelectField(choices=[('KABAGOPSSAN', 'KABAGOPSSAN'), ('KABAGMINSISSAN', 'KABAGMINSISSAN'), ('DANSATKOMSAN', 'DANSATKOMSAN'), ('DANSATPAMSAN', 'DANSATPAMSAN'), ('DANSATLIDSAN', 'DANSATLIDSAN'), ('BATIURMIN', 'BATIURMIN')], max_length=75)),
                ('Dispos', multiselectfield.db.fields.MultiSelectField(choices=[('Ump', 'Ump'), ('Udk', 'Udk'), ('Udl', 'Udl'), ('Siapkan', 'Siapkan'), ('Arsipkan', 'Arsipkan'), ('Pelajari', 'Pelajari'), ('Ikuti Perkembangannya', 'Ikuti Perkembangannya'), ('Laporkan Hasilnya', 'Laporkan Hasilnya'), ('Monitor', 'Monitor'), ('Sesuaikan Juk Danpussansiad', 'Sesuaikan Juk Danpussansiad')], max_length=113)),
                ('Perihall', models.TextField(default='')),
                ('Attachmentt', models.FileField(upload_to='filesimpan/attachments/')),
                ('catatan', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, unique=True)),
                ('tanggal_surat', models.DateField()),
                ('kategori', models.CharField(choices=[('Biasa', 'Biasa'), ('Segera', 'Segera'), ('Mendesak', 'Mendesak')], max_length=50)),
                ('klasifikasi', models.CharField(choices=[('Kilat', 'Kilat'), ('Express', 'Express'), ('Biasa', 'Biasa')], max_length=50)),
                ('tujuan', models.CharField(max_length=50)),
                ('pengirim', models.CharField(max_length=100)),
                ('perihal', models.TextField(default='')),
                ('attachment', models.FileField(upload_to='filesimpan/attachments/')),
                ('st_dispo', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
                ('st_arsip', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_dispo',
            fields=[
                ('id_dispo', models.AutoField(primary_key=True, serialize=False)),
                ('nm_dispo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_login', models.CharField(max_length=100)),
                ('nrp', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Analis', 'Analis'), ('Bagum', 'Bagum')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pejabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pejabat', models.CharField(max_length=50)),
                ('nrp', models.CharField(max_length=50)),
                ('id_jabatan', models.CharField(max_length=50)),
                ('nm_pejabat', models.CharField(max_length=50)),
                ('tmt_jab', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_suratmasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100)),
                ('tanggal_surat', models.DateField()),
                ('kategori', models.CharField(choices=[('Biasa', 'Biasa'), ('Segera', 'Segera'), ('Mendesak', 'Mendesak')], max_length=50)),
                ('klasifikasi', models.CharField(choices=[('Kilat', 'Kilat'), ('Express', 'Express'), ('Biasa', 'Biasa')], max_length=50)),
                ('tujuan', models.CharField(max_length=50)),
                ('pengirim', models.CharField(max_length=100)),
                ('perihal', models.TextField(default='')),
                ('attachment', models.FileField(upload_to='filesimpan/attachments/')),
                ('st_dispo', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
                ('st_arsip', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='tmt_bagian',
            fields=[
                ('id_bagian', models.AutoField(primary_key=True, serialize=False)),
                ('nm_bagian', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TSuratKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomor_surat', models.CharField(max_length=100, unique=True)),
                ('Tanggal_surat', models.DateField()),
                ('Kategori', models.CharField(choices=[('Biasa', 'Biasa'), ('Segera', 'Segera'), ('Mendesak', 'Mendesak')], max_length=50)),
                ('Klasifikasi', models.CharField(choices=[('Umum', 'Umum'), ('Khusus', 'Khusus'), ('Kilat', 'Kilat')], max_length=50)),
                ('Tujuan', models.CharField(max_length=100)),
                ('Tembusan', models.CharField(max_length=100)),
                ('Perihal', models.TextField(default='Default ')),
                ('Attachment', models.FileField(upload_to='filekeluar/attachments/')),
                ('st_arsip', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
            ],
        ),
    ]
